### ISSUE TITLE
V1.5 Tracking Issue

### ISSUE THREAD

**Issue by recmo** [worldcoin/iris-mpc#5]
- [x] Measure bandwidth without RDMA (NCCL sockets).
- [x] Measure bandwidth across organization domains (NCCL sockets).
- [x] Benchmark in target availability zone.
- [x] Benchmark on p5 instances.
- [x] Extensively test distances against reference implementation.
- [x] Implement v1 to v1.5 migration tool.
- [x] Implement async networking.
- [ ] Benchmark 32b implementation.
- [x] Benchmark phase 2 CUDA implementation.
- [ ] Add observability / telemetry / logging.
- [ ] Get CUDA + NCCL working in AWS Nitro Enclave.
- [ ] Test bandwidth from AWS Nitro Enclave.
- [ ] Benchmark from AWS Nitro Enclave.
- [ ] Produce and cross-check attestations from AWS Nitro Enclaves.
